[project]
name = "attendence-control-backend"
version = "0.1.0"
description = "The backend of the attendance control system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "uvicorn[standard]>=0.34.3",
]

[dependency-groups]
dev = [
    "fastapi-cli>=0.0.7",
    "ruff>=0.11.13",
]
