"""add timezone in app_config

Revision ID: 7d76089a9767
Revises: 0b129d078bf3
Create Date: 2025-07-30 20:47:09.049830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7d76089a9767'
down_revision: Union[str, Sequence[str], None] = '0b129d078bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appconfig', sa.Column('zone_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='UTC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appconfig', 'zone_info')
    # ### end Alembic commands ###
