"""add is_admin in role

Revision ID: 8a931c015d57
Revises: c5b434c5cc1b
Create Date: 2026-04-27 10:44:15.774927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8a931c015d57'
down_revision: Union[str, Sequence[str], None] = 'c5b434c5cc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'is_admin')
    # ### end Alembic commands ###
