"""add timestamp

Revision ID: c5b434c5cc1b
Revises: 7d76089a9767
Create Date: 2025-09-16 18:50:34.997659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c5b434c5cc1b'
down_revision: Union[str, Sequence[str], None] = '7d76089a9767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appconfig', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('appconfig', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('appconfig', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('attendance', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('dayoff', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('dayoff', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('dayoff', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('shift', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('shift', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('shift', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('shift', 'deleted_at')
    op.drop_column('shift', 'updated_at')
    op.drop_column('shift', 'created_at')
    op.drop_column('role', 'deleted_at')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_column('dayoff', 'deleted_at')
    op.drop_column('dayoff', 'updated_at')
    op.drop_column('dayoff', 'created_at')
    op.drop_column('attendance', 'deleted_at')
    op.drop_column('attendance', 'updated_at')
    op.drop_column('attendance', 'created_at')
    op.drop_column('appconfig', 'deleted_at')
    op.drop_column('appconfig', 'updated_at')
    op.drop_column('appconfig', 'created_at')
    # ### end Alembic commands ###
